add drawing to the grid + docs :3 (again)
ferry-creator/shelly.run pull request #2
Opened 2024-04-09 15:12 UTC by not-nullptr

2024-04-09 20:46 UTC, nemzyx requested changes
I put comments on the code 🤓✨ Thanks for contributing! I will merge once these minor changes have been addressed, this is an awesome feature!

2024-04-09 20:46 UTC, nemzyx commented on app/public/documentation.js
> +        clearScreen: {
Rename to clearPixels 👌

2024-04-09 20:46 UTC, nemzyx commented on app/src/components/Grid.svelte
> +  let pixels = [];
Remove semicolons 🤠

2024-04-09 20:46 UTC, nemzyx commented on app/src/components/Grid.svelte
> +    // todo : migrate to a canvas api to make it faster (this is fine for now)
Remove comment about Canvas API. It's not a todo! Your DOM implementation is perfect for this game, as hackability and ease of understanding is far more important than performance. With the DOM implementation, players can inspect element and get more familiar with HTML at the same time ✨

2024-04-09 20:46 UTC, nemzyx commented on app/src/components/Grid.svelte
> +    // it also handles screen capture pretty well (yes, doom was played on this)
Love these other comments lmao, thanks for contributing, maybe we should finish this together? 🔥 I have code from another project that can fix the next step on the roadmap (implement propper screenspace to worldspace transform, right now everything is 100% screenspace with no concept of a "world")

2024-04-09 20:46 UTC, nemzyx commented on app/src/components/Grid.svelte
> +<!-- this is pretty slow . todo: canvas api? :3c -->
Remove comment about Canvas API. It's not a todo! Your DOM implementation is perfect for this game 🔥🙏 (same as the other comment)

2024-04-09 22:32 UTC, not-nullptr reviewed
done in the new commit i think?

2024-04-09 23:33 UTC, nemzyx commented
Almost there - added a final comment, would be awesome if you can add to the README 🤠

2024-04-09 23:38 UTC, nemzyx commented
Also btw: practice coming up with better commit messages. "Fix problems" doesn't really describe your commit. You could have named the commit "remove todos, rename clearScreen to clearPixels" 👌

2024-04-12 15:59 UTC, not-nullptr commented
any updates on this? i've updated the readme n stuff

2024-04-15 16:12 UTC, nemzyx approved these changes
Amazing

2024-04-15 16:12 UTC, shdrs commented on app/src/components/Grid.svelte
> +    // another todo : add my super-cool examples to the docs (maybe in the readme?)
Yea 100% let's do this too! But while cool, remember shelly.run is meant to teach kids (or anyone really) how to code, so this feature is a little niche, thus I don't want it to take over the entire README 😃

1) Add section to bottom of README, just before the license section. Title it: Drawing pixels on grid demos

2) Then instead of directly putting your code there, make links to GISTS you create containing the sample code, and explain briefly what your experiment was about ☀️

By linking to GISTS instead of pasting your code we avoid it completely taking over the focus of the project 😎

2024-04-15 16:12 UTC, shdrs commented on app/src/components/Grid.svelte
> +    // another todo : add my super-cool examples to the docs (maybe in the readme?)
(Remember to use markdown links and make it as clear and concise as you can)

2024-04-15 16:13 UTC, merged